db: 
  host: localhost:27017
  #mongoURI: mongodb://localhost:27017
  mongoTLS: false
  datasetName: iotex_rewards

port: 8089

epochsController:
  interval: 600
  name: BPNAME
  startEpoch: 0
  bpAddress: BPADDRESS
  rewardsAddress: BPREWARDSADDRESS
  rewards:
    chainBlockRewards: 16000000000000000000
    chainBonusRewards: 80000000000000000000
    blockPercentage: 80
    epochPercentage: 80
    bonusPercentage: 80

payout:
  interval: 0 # number of epochs 24epochs~24h 0 to disable
  minAmount: 10000000000000000000
  claim: true
  gasLimit: 35000
  privateKey: REWARDSPRIVATEKEY #Account Private key fro Rewards Claim and Payout
  ioPayout: false
  ethAPI: https://mainnet.infura.io
  ethToken: 0x6fB3e0A217407EFFf7Ca062D46c26E5d60a14d69
  ethPrivateKey: ETHPRIVATEKEY
  ethGasLimit: 150000
  ethSendInterval: 20

committee:
  numOfRetries: 8
  gravityChainAPIs:
  - https://mainnet.infura.io/v3/b355cae6fafc4302b106b937ee6c15af
  gravityChainHeightInterval: 100
  gravityChainStartHeight: 7368630
  registerContractAddress: 0x95724986563028deb58f15c5fac19fa09304f32d
  stakingContractAddress: 0x87c9dbff0016af23f5b1ab9b8e072124ab729193
  paginationSize: 100
  voteThreshold: "0"
  scoreThreshold: "0"
  selfStakingThreshold: "0"
  cacheSize: 100
