db: 
  host: localhost:27017
  #mongoURI: mongodb://localhost:27017
  mongoTLS: false
  datasetName: iotex_rewards

port: 8089

epochsController:
  endpoint: api.iotex.one:80
  name: BPNAME
  startEpoch: 0
  bpAddress: BPADDRESS
  rewardsAddress: BPREWARDSADDRESS
  rewards:
    chainBlockRewards: 16000000000000000000
    chainBonusRewards: 80000000000000000000
    blockPercentage: 80
    epochPercentage: 80
    bonusPercentage: 80

committee:
  numOfRetries: 8
  gravityChainAPIs:
  - https://mainnet.infura.io/v3/b355cae6fafc4302b106b937ee6c15af
  gravityChainHeightInterval: 100
  gravityChainStartHeight: 7368630
  registerContractAddress: 0x95724986563028deb58f15c5fac19fa09304f32d
  stakingContractAddress: 0x87c9dbff0016af23f5b1ab9b8e072124ab729193
  paginationSize: 100
  voteThreshold: "0"
  scoreThreshold: "0"
  selfStakingThreshold: "0"
  cacheSize: 100
